/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: netpoker.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "netpoker.pb-c.h"
void   card__init
                     (Card         *message)
{
  static const Card init_value = CARD__INIT;
  *message = init_value;
}
size_t card__get_packed_size
                     (const Card *message)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t card__pack
                     (const Card *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t card__pack_to_buffer
                     (const Card *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Card *
       card__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Card *)
     protobuf_c_message_unpack (&card__descriptor,
                                allocator, len, data);
}
void   card__free_unpacked
                     (Card *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &card__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hand__init
                     (Hand         *message)
{
  static const Hand init_value = HAND__INIT;
  *message = init_value;
}
size_t hand__get_packed_size
                     (const Hand *message)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hand__pack
                     (const Hand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hand__pack_to_buffer
                     (const Hand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hand *
       hand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hand *)
     protobuf_c_message_unpack (&hand__descriptor,
                                allocator, len, data);
}
void   hand__free_unpacked
                     (Hand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hand__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pos__init
                     (Pos         *message)
{
  static const Pos init_value = POS__INIT;
  *message = init_value;
}
size_t pos__get_packed_size
                     (const Pos *message)
{
  assert(message->base.descriptor == &pos__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pos__pack
                     (const Pos *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pos__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pos__pack_to_buffer
                     (const Pos *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pos__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pos *
       pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pos *)
     protobuf_c_message_unpack (&pos__descriptor,
                                allocator, len, data);
}
void   pos__free_unpacked
                     (Pos *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pos__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   player__init
                     (Player         *message)
{
  static const Player init_value = PLAYER__INIT;
  *message = init_value;
}
size_t player__get_packed_size
                     (const Player *message)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player__pack
                     (const Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player__pack_to_buffer
                     (const Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Player *
       player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Player *)
     protobuf_c_message_unpack (&player__descriptor,
                                allocator, len, data);
}
void   player__free_unpacked
                     (Player *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor card__field_descriptors[2] =
{
  {
    "face_val",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Card, face_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Card, suit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned card__field_indices_by_name[] = {
  0,   /* field[0] = face_val */
  1,   /* field[1] = suit */
};
static const ProtobufCIntRange card__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor card__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Card",
  "Card",
  "Card",
  "",
  sizeof(Card),
  2,
  card__field_descriptors,
  card__field_indices_by_name,
  1,  card__number_ranges,
  (ProtobufCMessageInit) card__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hand__field_descriptors[1] =
{
  {
    "card",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Hand, n_card),
    offsetof(Hand, card),
    &card__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hand__field_indices_by_name[] = {
  0,   /* field[0] = card */
};
static const ProtobufCIntRange hand__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hand__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Hand",
  "Hand",
  "Hand",
  "",
  sizeof(Hand),
  1,
  hand__field_descriptors,
  hand__field_indices_by_name,
  1,  hand__number_ranges,
  (ProtobufCMessageInit) hand__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pos__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pos, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pos, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pos__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange pos__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pos__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Pos",
  "Pos",
  "Pos",
  "",
  sizeof(Pos),
  2,
  pos__field_descriptors,
  pos__field_indices_by_name,
  1,  pos__number_ranges,
  (ProtobufCMessageInit) pos__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor player__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Player, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Player, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Player, pos),
    &pos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hand",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Player, hand),
    &hand__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chips",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Player, chips),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player__field_indices_by_name[] = {
  4,   /* field[4] = chips */
  3,   /* field[3] = hand */
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  2,   /* field[2] = pos */
};
static const ProtobufCIntRange player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Player",
  "Player",
  "Player",
  "",
  sizeof(Player),
  5,
  player__field_descriptors,
  player__field_indices_by_name,
  1,  player__number_ranges,
  (ProtobufCMessageInit) player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
