/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: netpoker.proto */

#ifndef PROTOBUF_C_netpoker_2eproto__INCLUDED
#define PROTOBUF_C_netpoker_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct SocketInfo SocketInfo;


/* --- enums --- */


/* --- messages --- */

struct  SocketInfo
{
  ProtobufCMessage base;
  char *host;
  char *port;
  int32_t sockfd;
};
#define SOCKET_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&socket_info__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/* SocketInfo methods */
void   socket_info__init
                     (SocketInfo         *message);
size_t socket_info__get_packed_size
                     (const SocketInfo   *message);
size_t socket_info__pack
                     (const SocketInfo   *message,
                      uint8_t             *out);
size_t socket_info__pack_to_buffer
                     (const SocketInfo   *message,
                      ProtobufCBuffer     *buffer);
SocketInfo *
       socket_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   socket_info__free_unpacked
                     (SocketInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SocketInfo_Closure)
                 (const SocketInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor socket_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_netpoker_2eproto__INCLUDED */
