/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: netpoker.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "netpoker.pb-c.h"
void   socket_info__init
                     (SocketInfo         *message)
{
  static const SocketInfo init_value = SOCKET_INFO__INIT;
  *message = init_value;
}
size_t socket_info__get_packed_size
                     (const SocketInfo *message)
{
  assert(message->base.descriptor == &socket_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t socket_info__pack
                     (const SocketInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &socket_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t socket_info__pack_to_buffer
                     (const SocketInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &socket_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SocketInfo *
       socket_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SocketInfo *)
     protobuf_c_message_unpack (&socket_info__descriptor,
                                allocator, len, data);
}
void   socket_info__free_unpacked
                     (SocketInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &socket_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor socket_info__field_descriptors[3] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SocketInfo, host),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SocketInfo, port),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sockfd",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SocketInfo, sockfd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned socket_info__field_indices_by_name[] = {
  0,   /* field[0] = host */
  1,   /* field[1] = port */
  2,   /* field[2] = sockfd */
};
static const ProtobufCIntRange socket_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor socket_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SocketInfo",
  "SocketInfo",
  "SocketInfo",
  "",
  sizeof(SocketInfo),
  3,
  socket_info__field_descriptors,
  socket_info__field_indices_by_name,
  1,  socket_info__number_ranges,
  (ProtobufCMessageInit) socket_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
