name: AppImage Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Install required dependencies
      run: |
        sudo apt-get install -y \
          meson \
          libprotobuf-c-dev \
          libsdl2-dev \
          libsdl2-ttf-dev

    # Runs a set of commands using the runners shell
    - name: Download building tools & executing AppImage build
      run: |
        wget -nv -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
        chmod +x pyuploadtool-x86_64.AppImage
    - run: |
        meson setup _build2 \
          -Dprefix=/usr \
          --buildtype=release \
          -Dbuild_netpoker=true \
          -Db_sanitize=none
        cd _build
        ninja
        DESTDIR=AppDir ninja -v install
        ../linuxdeploy-x86_64.AppImage \
          --executable AppDir/usr/bin/aapokerhands \
          --icon-file=../aapokerhands.png \
          --icon-filename=aapokerhands \
          --create-desktop-file \
          --appdir $PWD/AppDir --output appimage
        ../pyuploadtool-x86_64.AppImage aapokerhands*AppImage
