name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Dependencies
      run: sudo apt-get install -y meson
    - run: |
        meson setup _build -Db_sanitize=address,undefined
        cd _build
        ninja -v
        src/aapokerhands -n 100 -v -s
        ninja dist

  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        brew update
        brew install meson
    - run: |
        meson setup _build -Db_sanitize=address,undefined
        cd _build
        ninja -v
        src/aapokerhands -n 100 -v -s
        ninja dist
